version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: /server
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-app
    depends_on:
      - mongo

  frontend:
    build: /client
    container_name: frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data: